"use client"

import Link from "next/link"

interface HeroProps {
  email: string
  setEmail: (email: string) => void
}

export default function Hero({ email, setEmail }: HeroProps) {
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (email) {
      window.location.href = `/signup?email=${encodeURIComponent(email)}`
    }
  }

  return (
    <section className="hero-gradient pt-32 pb-20 px-4 sm:px-6 lg:px-8">
      <div className="max-w-5xl mx-auto text-center">
        <div className="inline-flex items-center gap-2 bg-blue-50 border border-blue-100 rounded-full px-4 py-2 mb-8">
          <div className="w-2 h-2 rounded-full bg-blue-500 animate-pulse" />
          <span className="text-blue-700 text-sm font-medium">
            14-day free trial · No credit card required
          </span>
        </div>

        <h1 className="text-5xl sm:text-6xl lg:text-7xl font-bold text-gray-900 leading-tight tracking-tight mb-6">
          Turn LinkedIn into your{" "}
          <span className="gradient-text">#1 B2B lead source</span>
        </h1>

        <p className="text-xl sm:text-2xl text-gray-500 max-w-3xl mx-auto mb-10 leading-relaxed">
          AI-powered content engine built for consultants, coaches, and agency owners who need to{" "}
          <strong className="text-gray-700">attract premium clients</strong> — not just followers.
        </p>

        <form onSubmit={handleSubmit} className="flex flex-col sm:flex-row gap-3 max-w-lg mx-auto mb-6">
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="Enter your work email"
            className="flex-1 px-5 py-4 rounded-full border border-gray-200 text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-base"
            required
          />
          <button
            type="submit"
            className="gradient-bg text-white font-semibold px-8 py-4 rounded-full hover:opacity-90 transition-opacity text-base whitespace-nowrap glow-pulse"
          >
            Start for free →
          </button>
        </form>

        <p className="text-gray-400 text-sm mb-16">
          Join 500+ B2B professionals already generating leads with Spur AI
        </p>

        <div className="relative mx-auto max-w-4xl">
          <div className="bg-white rounded-2xl shadow-2xl border border-gray-100 overflow-hidden">
            <div className="bg-gray-50 px-4 py-3 flex items-center gap-2 border-b border-gray-100">
              <div className="w-3 h-3 rounded-full bg-red-400" />
              <div className="w-3 h-3 rounded-full bg-yellow-400" />
              <div className="w-3 h-3 rounded-full bg-green-400" />
              <span className="text-gray-400 text-xs ml-2">Spur AI — Post Generator</span>
            </div>
            <div className="p-6">
              <div className="flex gap-4 mb-4">
                <div className="w-10 h-10 rounded-full gradient-bg flex-shrink-0" />
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-semibold text-gray-900 text-sm">Your Name</span>
                    <span className="text-gray-400 text-xs">• 1st</span>
                  </div>
                  <span className="text-gray-500 text-xs">Marketing Agency Owner | 487 followers</span>
                </div>
              </div>
              <div className="text-gray-800 text-sm leading-relaxed space-y-2">
                <p className="font-semibold">I turned down a $50K contract last month.</p>
                <p>Not because we couldn&apos;t deliver. But because they weren&apos;t the right fit.</p>
                <p>3 years ago, I would&apos;ve taken it anyway. Here&apos;s what changed:</p>
                <div className="pl-4 space-y-1 text-gray-600">
                  <p>→ We niched down to SaaS companies $1M-$10M ARR</p>
                  <p>→ We raised our minimum engagement to $8K/mo</p>
                  <p>→ We started saying no to wrong-fit clients</p>
                </div>
                <p>Result? Revenue went up 40% in 6 months.</p>
                <p className="text-blue-600">What was the best &ldquo;no&rdquo; you ever said in business?</p>
              </div>
              <div className="mt-4 flex items-center gap-4 text-gray-400 text-xs">
                <span>👍 247 reactions</span>
                <span>💬 89 comments</span>
                <span>🔄 34 reposts</span>
              </div>
              <div className="mt-3 flex items-center gap-1 text-xs text-green-600 font-medium">
                <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
                Generated by Spur AI in 8 seconds
              </div>
            </div>
          </div>

          <div className="absolute -top-4 -right-4 bg-white rounded-xl shadow-lg border border-gray-100 px-4 py-3 float-animation">
            <div className="flex items-center gap-2">
              <span className="text-2xl">🚀</span>
              <div>
                <div className="text-xs font-semibold text-gray-800">3 new leads today</div>
                <div className="text-xs text-gray-400">from your last post</div>
              </div>
            </div>
          </div>

          <div className="absolute -bottom-4 -left-4 bg-white rounded-xl shadow-lg border border-gray-100 px-4 py-3 float-animation" style={{ animationDelay: "2s" }}>
            <div className="flex items-center gap-2">
              <span className="text-2xl">💰</span>
              <div>
                <div className="text-xs font-semibold text-gray-800">$24,000 deal closed</div>
                <div className="text-xs text-gray-400">prospect from LinkedIn</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
